name: homesync
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter 
  fl_chart: ^1.1.0
  weather: ^3.1.0
  time_range_picker: ^2.3.0
  intl: ^0.20.2
  cupertino_icons: ^1.0.8
  flutter_native_splash: ^2.4.5
  google_fonts: ^6.2.1
  shared_preferences: ^2.5.2
  firebase_database: ^12.0.1
  firebase_core: ^4.1.0
  cloud_firestore: ^6.0.1
  firebase_auth: ^6.0.2
  firebase_messaging: ^16.0.1
  flutter_local_notifications: ^19.4.2
  flutter_background_service: ^5.0.10
  flutter_background_service_android: ^6.3.1
  mailer: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  assets:
    - assets/homesync_logo.png
  uses-material-design: true

flutter_native_splash:
  color: "#ffffff"
  image: assets/homesync_logo.png
  android: true
  ios: true
