// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;
import 'package:homesync/config.dart';

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB3Ig1-6ry5QsE3L57R5nQ2lwNibeh3MBE',
    appId: '1:258697759332:web:7ab12d4a96191be43b2d71',
    messagingSenderId: '258697759332',
    projectId: 'homeautomation-b6d6d',
    authDomain: 'homeautomation-b6d6d.firebaseapp.com',
    databaseURL: 'https://homeautomation-b6d6d-default-rtdb.firebaseio.com',
    storageBucket: 'homeautomation-b6d6d.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: API_KEY,
    appId: '1:258697759332:android:9c63bb5a2b0772fe3b2d71',
    messagingSenderId: '258697759332',
    projectId: 'homeautomation-b6d6d',
    databaseURL: 'https://homeautomation-b6d6d-default-rtdb.firebaseio.com',
    storageBucket: 'homeautomation-b6d6d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAi68LofjxMiyB7LHJ0U53-urOo5-7FjcA',
    appId: '1:258697759332:ios:7620bdfd38bcb3d13b2d71',
    messagingSenderId: '258697759332',
    projectId: 'homeautomation-b6d6d',
    databaseURL: 'https://homeautomation-b6d6d-default-rtdb.firebaseio.com',
    storageBucket: 'homeautomation-b6d6d.firebasestorage.app',
    iosBundleId: 'com.example.homesync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAi68LofjxMiyB7LHJ0U53-urOo5-7FjcA',
    appId: '1:258697759332:ios:7620bdfd38bcb3d13b2d71',
    messagingSenderId: '258697759332',
    projectId: 'homeautomation-b6d6d',
    databaseURL: 'https://homeautomation-b6d6d-default-rtdb.firebaseio.com',
    storageBucket: 'homeautomation-b6d6d.firebasestorage.app',
    iosBundleId: 'com.example.homesync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB3Ig1-6ry5QsE3L57R5nQ2lwNibeh3MBE',
    appId: '1:258697759332:web:3de7c66d6a09a7903b2d71',
    messagingSenderId: '258697759332',
    projectId: 'homeautomation-b6d6d',
    authDomain: 'homeautomation-b6d6d.firebaseapp.com',
    databaseURL: 'https://homeautomation-b6d6d-default-rtdb.firebaseio.com',
    storageBucket: 'homeautomation-b6d6d.firebasestorage.app',
  );

}
